/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_czt_ndk_helloworld_MainActivity */

#ifndef _Included_com_czt_ndk_helloworld_MainActivity
#define _Included_com_czt_ndk_helloworld_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_czt_ndk_helloworld_MainActivity
 * Method:    helloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_czt_ndk_helloworld_MainActivity_helloFromC
  (JNIEnv *, jobject);

/*
 * Class:     com_czt_ndk_helloworld_MainActivity
 * Method:    hello_from_c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_czt_ndk_helloworld_MainActivity_hello_1from_1c
  (JNIEnv *, jobject);

/*
 * Class:     com_czt_ndk_helloworld_MainActivity
 * Method:    helloFromJavahC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_czt_ndk_helloworld_MainActivity_helloFromJavahC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
