/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_czt_lame_MainActivity */

#ifndef _Included_com_czt_lame_MainActivity
#define _Included_com_czt_lame_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_czt_lame_MainActivity
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_czt_lame_MainActivity_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_czt_lame_MainActivity
 * Method:    convert
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_czt_lame_MainActivity_convert
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_czt_lame_MainActivity
 * Method:    stopConvert
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_czt_lame_MainActivity_stopConvert
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
