/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_czt_usingcpp_MainActivity */

#ifndef _Included_com_czt_usingcpp_MainActivity
#define _Included_com_czt_usingcpp_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_czt_usingcpp_MainActivity
 * Method:    helloFromCpp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_czt_usingcpp_MainActivity_helloFromCpp
  (JNIEnv *, jobject);

/*
 * Class:     com_czt_usingcpp_MainActivity
 * Method:    sayHelloInCpp
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_czt_usingcpp_MainActivity_sayHelloInCpp
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
