/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_czt_ndk_monitor_DemoActivity */

#ifndef _Included_com_czt_ndk_monitor_DemoActivity
#define _Included_com_czt_ndk_monitor_DemoActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_czt_ndk_monitor_DemoActivity
 * Method:    getCurrentPressure
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_czt_ndk_monitor_DemoActivity_getCurrentPressure
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
